services:
  postgres:
    image: postgres:latest
    container_name: postgres_Fitech
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:7.3.0-alpine
    environment:
      - FLYWAY_USER=${FLYWAY_USER}
      - FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/FiTech
    depends_on:
      - postgres
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
  
  flyway_repair:
    image: flyway/flyway:7.3.0-alpine
    environment:
      - FLYWAY_USER=${FLYWAY_USER}
      - FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./flyway/sql:/flyway/sql
    command: repair


  adminer:
    image: adminer
    container_name: adminer_FiTech
    ports:
      - 8080:8080


volumes:
  pgdata: